/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package systemAdmin;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Doctor;
import model.cityArrayList;
import model.communityArrayList;
import model.doctorArrayList;
import model.hospitalArrayList;
import model.houseArrayList;
import model.patientArrayList;

/**
 *
 * @author DELL
 */
public class doctorSysAdmin extends javax.swing.JPanel {

    /**
     * Creates new form doctorSysAdmin
     */
    doctorArrayList d;
    hospitalArrayList h;
    cityArrayList c;
    communityArrayList co;
    houseArrayList ho;
    public doctorSysAdmin(doctorArrayList d,hospitalArrayList h,cityArrayList c,communityArrayList co,houseArrayList ho) {
        initComponents();
        this.d = d;
        this.c=c;
        this.co=co;
        this.ho=ho;
        this.h=h;
        populateTable();
        populateCity();
        populateCountry();
        populateState();
        populateCommunity();
        populateZipcode();
        populateHospitalname();
        populateHospitaladd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlePatient = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabled = new javax.swing.JTable();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        doctorid = new javax.swing.JTextField();
        lblName5 = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        view = new javax.swing.JButton();
        lblName7 = new javax.swing.JLabel();
        cellphone = new javax.swing.JTextField();
        lblName8 = new javax.swing.JLabel();
        Search = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        search = new javax.swing.JTextArea();
        hcity = new javax.swing.JComboBox<>();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        lblName9 = new javax.swing.JLabel();
        lblName10 = new javax.swing.JLabel();
        lblName11 = new javax.swing.JLabel();
        hresidence = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        zipcode = new javax.swing.JComboBox<>();
        hcommunity = new javax.swing.JComboBox<>();
        hstate = new javax.swing.JComboBox<>();
        lblName12 = new javax.swing.JLabel();
        hcountry = new javax.swing.JComboBox<>();
        lblName13 = new javax.swing.JLabel();
        hname = new javax.swing.JComboBox<>();

        titlePatient.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        titlePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePatient.setText("             Doctor Details");
        titlePatient.setToolTipText("");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name");

        tabled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Doctor ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabled);

        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName1.setText("Age");

        lblName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName2.setText("Gender");

        lblName3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName3.setText("Hospital Residence");

        lblName4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName4.setText("Hospital City");

        doctorid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctoridActionPerformed(evt);
            }
        });

        lblName5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName5.setText("Hospital Community");

        lblName6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName6.setText("Doctor ID");

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        lblName7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName7.setText("Hospital Name");

        lblName8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName8.setText("Cell Phone");

        Search.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Search.setText("Search");

        search.setColumns(20);
        search.setRows(5);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(search);

        hcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        lblName9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName9.setText("Username");

        lblName10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName10.setText("Password");

        lblName11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName11.setText("Zipcode");

        hresidence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        zipcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        hcommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        hstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        lblName12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName12.setText("Hospital State");

        hcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        lblName13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName13.setText("Hospital Country");

        hname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female", "Other" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName13, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(lblName6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lblName4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblName2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addComponent(lblName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName5, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hcity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hresidence, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hstate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(864, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(titlePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titlePatient)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName)
                            .addComponent(lblName7)
                            .addComponent(hname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName1)
                            .addComponent(hresidence, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName3))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName2)
                            .addComponent(hcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName6)
                            .addComponent(hcity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName4))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName9)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName12)
                            .addComponent(hstate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName13)
                            .addComponent(lblName10)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName11)
                            .addComponent(cellphone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName8))))
                .addGap(0, 766, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        int row = tabled.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this,"Please select row to delete");
            return;

        }

        DefaultTableModel model = (DefaultTableModel) tabled.getModel();
        Doctor selectedep = (Doctor)model.getValueAt(row, 0);

        name.setText(String.valueOf(selectedep.getName()));
        age.setText(String.valueOf(selectedep.getAge()));
        gender.setSelectedItem(String.valueOf(selectedep.getGender()));
        hresidence.setSelectedItem(String.valueOf(selectedep.getHospitalResidence()));
        hcommunity.setSelectedItem(String.valueOf(selectedep.getCommunity()));
        doctorid.setText(String.valueOf(selectedep.getDoctorId()));
        hcity.setSelectedItem(String.valueOf(selectedep.getCity()));
        hname.setSelectedItem(String.valueOf(selectedep.getHospitalName()));
        cellphone.setText(String.valueOf(selectedep.getCellPhone()));
        username.setText(String.valueOf(selectedep.getUsername()));
        password.setText(String.valueOf(selectedep.getPassword()));
        zipcode.setSelectedItem(String.valueOf(selectedep.getZipcode()));
        hstate.setSelectedItem(String.valueOf(selectedep.getState()));
        hcountry.setSelectedItem(String.valueOf(selectedep.getCountry()));
        

    }//GEN-LAST:event_viewActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int row = tabled.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this,"Please select row to delete");
            return;

        }

        DefaultTableModel model = (DefaultTableModel) tabled.getModel();
        Doctor selectedep = (Doctor)model.getValueAt(row, 0);

        d.deleteD(selectedep);
        JOptionPane.showMessageDialog(this,"Doctor Profile deleted");

        populateTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int row = tabled.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this,"Please select row to delete");
            return;

        }

        DefaultTableModel model = (DefaultTableModel) tabled.getModel();
        Doctor selectedep = (Doctor)model.getValueAt(row, 0);
        d.deleteD(selectedep);
        int flag =1;
        String s1 = name.getText(); 
        if(s1.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars = s1.toCharArray();
        for(char c : chars)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
        
        
        String ss2 = age.getText();             
        
        if(ss2.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Age field cannot be empty or contain alphabet"); 
           return;
        }
        char[] chars1 = ss2.toCharArray();
        for(char c : chars1)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Age field cannot be empty or contain alphabet"); 
               return;   
            }
        }
        int s2 = Integer.parseInt(ss2);
          
        String s3 = (String)gender.getSelectedItem();
        if(s3.equals("select"))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Gender field cannot be empty");  
           return;
        }
        String ss4 = doctorid.getText();
        
         if(ss4.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
           return;
        }
        char[] chars3 = ss4.toCharArray();
        for(char c : chars3)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
               return;   
            }
        }
        int s4 = Integer.parseInt(ss4);
        for (Doctor epp:d.getD()){
            if (s4 == (epp.getDoctorId())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"ID already exists, please fill the details again");
            }
        }
        
        String s5 = username.getText();
        if(s5.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Username field cannot be empty");
           return;                     
        } 
         for (Doctor ep:d.getD()){
            if (s5.equals(ep.getUsername())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"Username already exists, please try again");
            }
         }
            
            String s6 = password.getText();
             if(s6.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Password field cannot be empty");
           return;                     
        } 
         for (Doctor ep1:d.getD()){
            if (s6.equals(ep1.getPassword())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"Password already exists, please try again");
            }
        
        
        } 

        String ss7 =  cellphone.getText();
        
        if(ss7.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Cell phone number field cannot be empty or contain alphabet"); 
           return;
         }
        if(ss7.length()!=10)
        {
            flag=0;
            JOptionPane.showMessageDialog(this,"Cell phone number must be 10 digits");  
            return;
        }
        char[] chars5 = ss7.toCharArray();
        for(char c : chars5)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Cell phone number field cannot be empty or contain alphabet"); 
               return;   
            }
        }
       
         
        long s7 = Long.parseLong(ss7);
         for (Doctor epp:d.getD()){
            if (s7 == (epp.getCellPhone())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"Phone Number already exists, please fill the details again");
            }
         }
        String s8 = (String)hname.getSelectedItem();
        if(s8.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital Name cannot be empty or have numbers");
            return;
        }
       char[] chars6 = s8.toCharArray();
       for(char c: chars6){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital Name cannot be empty or have numbers");
            return;
               
           }
       }  
        String s9 = (String)hresidence.getSelectedItem();
       
       if(s9.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital Residence cannot be empty");
            return;
        }
        
       String s10 = (String)hcommunity.getSelectedItem();
       
       if(s10.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this," Hospital Community cannot be empty or have numbers");
            return;
        }
       char[] chars7 = s10.toCharArray();
       for(char c: chars7){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital Community cannot be empty or have numbers");
            return;
               
           }
       }
       String s11 = (String)hcity.getSelectedItem();
       
       if(s11.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital City cannot be empty or have numbers");
            return;
        }
       char[] chars8 = s11.toCharArray();
       for(char c: chars8){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital City cannot be empty or have numbers");
            return;
               
           }
       }
       String s12 = (String)hstate.getSelectedItem();
       
       if(s12.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital State cannot be empty or have numbers");
            return;
        }
       char[] chars9 = s12.toCharArray();
       for(char c: chars9){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital State cannot be empty or have numbers");
            return;
               
           }
       }
       String s13 = (String)hcountry.getSelectedItem();
       
       if(s13.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital Country cannot be empty or have numbers");
            return;
        }
       char[] chars10 = s13.toCharArray();
       for(char c: chars10){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital Country cannot be empty or have numbers");
            return;
               
           }
       }
       String ss14 = (String)zipcode.getSelectedItem();
        
        if(ss14.equals("select")){
            flag=0;
            JOptionPane.showMessageDialog(this,"Hospital Zipcode cannot be empty or have alphabets");
            return;
        }
        char[] chars12 = ss14.toCharArray();
        for(char c: chars12){
            if(Character.isAlphabetic(c)){
                flag=0;
                JOptionPane.showMessageDialog(this,"Hospital Zipcode cannot be empty or have alphabets");
                return;
                
            }
        }
        long s14 = Long.parseLong(ss14);  
       
        if(flag == 1)
        {
        Doctor pp = d.addNewD();
        pp.setName(s1);
        pp.setAge(s2);
        pp.setGender(s3);
        pp.setDoctorId(s4);
        pp.setUsername(s5);
        pp.setPassword(s6);
        pp.setCellPhone(s7);
        pp.setHospitalName(s8);
        pp.setHospitalResidence(s9);
        pp.setCommunity(s10);
        pp.setCity(s11);
        pp.setState(s12);
        pp.setCountry(s13);              
        pp.setZipcode(s14);
         
         
        JOptionPane.showMessageDialog(this,"Doctor Profile updated successfully"); 
          
           populateTable();
           
        
           
          
        }
        name.setText("");
        age.setText("");
        gender.setSelectedItem("select");
        hresidence.setSelectedItem("select");
        cellphone.setText("");
        hcommunity.setSelectedItem("select");
        zipcode.setSelectedItem("select");
        doctorid.setText("");
        username.setText("");
        password.setText(""); 
        hcountry.setSelectedItem("select");
        hstate.setSelectedItem("select");
        hcity.setSelectedItem("select");      
        hname.setSelectedItem("select");

    }//GEN-LAST:event_updateActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        int flag =1;
        String s1 = name.getText(); 
        if(s1.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars = s1.toCharArray();
        for(char c : chars)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
        
        
        String ss2 = age.getText();             
        
        if(ss2.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Age field cannot be empty or contain alphabet"); 
           return;
        }
        char[] chars1 = ss2.toCharArray();
        for(char c : chars1)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Age field cannot be empty or contain alphabet"); 
               return;   
            }
        }
        int s2 = Integer.parseInt(ss2);
          
        String s3 = (String)gender.getSelectedItem();
        if(s3.equals("select"))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Gender field cannot be empty");  
           return;
        }
        String ss4 = doctorid.getText();
        
         if(ss4.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
           return;
        }
        char[] chars3 = ss4.toCharArray();
        for(char c : chars3)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
               return;   
            }
        }
        int s4 = Integer.parseInt(ss4);
        for (Doctor epp:d.getD()){
            if (s4 == (epp.getDoctorId())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"ID already exists, please fill the details again");
            }
        }
        
        String s5 = username.getText();
        if(s5.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Username field cannot be empty");
           return;                     
        } 
         for (Doctor ep:d.getD()){
            if (s5.equals(ep.getUsername())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"Username already exists, please try again");
            }
         }
            
            String s6 = password.getText();
             if(s6.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Password field cannot be empty");
           return;                     
        } 
         for (Doctor ep1:d.getD()){
            if (s6.equals(ep1.getPassword())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"Password already exists, please try again");
            }
        
        
        } 

        String ss7 =  cellphone.getText();
        
        if(ss7.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Cell phone number field cannot be empty or contain alphabet"); 
           return;
         }
        if(ss7.length()!=10)
        {
            flag=0;
            JOptionPane.showMessageDialog(this,"Cell phone number must be 10 digits");  
            return;
        }
        char[] chars5 = ss7.toCharArray();
        for(char c : chars5)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Cell phone number field cannot be empty or contain alphabet"); 
               return;   
            }
        }
       
         
        long s7 = Long.parseLong(ss7);
         for (Doctor epp:d.getD()){
            if (s7 == (epp.getCellPhone())){
               flag=0;                
             JOptionPane.showMessageDialog(this,"Phone Number already exists, please fill the details again");
            }
         }
        String s8 = (String)hname.getSelectedItem();
        if(s8.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital Name cannot be empty or have numbers");
            return;
        }
       char[] chars6 = s8.toCharArray();
       for(char c: chars6){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital Name cannot be empty or have numbers");
            return;
               
           }
       }  
        String s9 = (String)hresidence.getSelectedItem();
       
       if(s9.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital Residence cannot be empty");
            return;
        }
        
       String s10 = (String)hcommunity.getSelectedItem();
       
       if(s10.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this," Hospital Community cannot be empty or have numbers");
            return;
        }
       char[] chars7 = s10.toCharArray();
       for(char c: chars7){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital Community cannot be empty or have numbers");
            return;
               
           }
       }
       String s11 = (String)hcity.getSelectedItem();
       
       if(s11.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital City cannot be empty or have numbers");
            return;
        }
       char[] chars8 = s11.toCharArray();
       for(char c: chars8){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital City cannot be empty or have numbers");
            return;
               
           }
       }
       String s12 = (String)hstate.getSelectedItem();
       
       if(s12.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital State cannot be empty or have numbers");
            return;
        }
       char[] chars9 = s12.toCharArray();
       for(char c: chars9){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital State cannot be empty or have numbers");
            return;
               
           }
       }
       String s13 = (String)hcountry.getSelectedItem();
       
       if(s13.equals("select")){
           flag=0;
           JOptionPane.showMessageDialog(this,"Hospital Country cannot be empty or have numbers");
            return;
        }
       char[] chars10 = s13.toCharArray();
       for(char c: chars10){
           if(Character.isDigit(c)){
               flag=0;
               JOptionPane.showMessageDialog(this,"Hospital Country cannot be empty or have numbers");
            return;
               
           }
       }
       String ss14 = (String)zipcode.getSelectedItem();
        
        if(ss14.equals("select")){
            flag=0;
            JOptionPane.showMessageDialog(this,"Hospital Zipcode cannot be empty or have alphabets");
            return;
        }
        char[] chars12 = ss14.toCharArray();
        for(char c: chars12){
            if(Character.isAlphabetic(c)){
                flag=0;
                JOptionPane.showMessageDialog(this,"Hospital Zipcode cannot be empty or have alphabets");
                return;
                
            }
        }
        long s14 = Long.parseLong(ss14);  
       
        if(flag == 1)
        {
        Doctor pp = d.addNewD();
        pp.setName(s1);
        pp.setAge(s2);
        pp.setGender(s3);
        pp.setDoctorId(s4);
        pp.setUsername(s5);
        pp.setPassword(s6);
        pp.setCellPhone(s7);
        pp.setHospitalName(s8);
        pp.setHospitalResidence(s9);
        pp.setCommunity(s10);
        pp.setCity(s11);
        pp.setState(s12);
        pp.setCountry(s13);              
        pp.setZipcode(s14);
         
         
        JOptionPane.showMessageDialog(this,"Doctor Profile created successfully"); 
          
           populateTable();
           
        
           
          
        }
        name.setText("");
        age.setText("");
        gender.setSelectedItem("select");
        hresidence.setSelectedItem("select");
        cellphone.setText("");
        hcommunity.setSelectedItem("select");
        zipcode.setSelectedItem("select");
        doctorid.setText("");
        username.setText("");
        password.setText(""); 
        hcountry.setSelectedItem("select");
        hstate.setSelectedItem("select");
        hcity.setSelectedItem("select");      
        hname.setSelectedItem("select");

      
        
        
        
    }//GEN-LAST:event_createActionPerformed

    private void doctoridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctoridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctoridActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabled.getModel();
        String value = search.getText();
        TableRowSorter<DefaultTableModel> key = new TableRowSorter<DefaultTableModel>(model);
        tabled.setRowSorter(key);
        key.setRowFilter(RowFilter.regexFilter(value));
    }//GEN-LAST:event_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Search;
    private javax.swing.JTextField age;
    private javax.swing.JTextField cellphone;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JTextField doctorid;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JComboBox<String> hcity;
    private javax.swing.JComboBox<String> hcommunity;
    private javax.swing.JComboBox<String> hcountry;
    private javax.swing.JComboBox<String> hname;
    private javax.swing.JComboBox<String> hresidence;
    private javax.swing.JComboBox<String> hstate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName11;
    private javax.swing.JLabel lblName12;
    private javax.swing.JLabel lblName13;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextArea search;
    private javax.swing.JTable tabled;
    private javax.swing.JLabel titlePatient;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    private javax.swing.JButton view;
    private javax.swing.JComboBox<String> zipcode;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
          DefaultTableModel model = (DefaultTableModel) tabled.getModel();
          model.setRowCount(0);
        
        for (Doctor ep:d.getD()){
            
            Object[] row = new Object[2];
            row[0] = ep;
            row[1] = ep.getDoctorId();
            
            model.addRow(row);
            
        }
        
    }
private void populateCity(){
     String[] cc = c.cityArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     hcity.setModel(c);
     
 
}
private void populateCountry(){
     String[] cc = c.countryArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     hcountry.setModel(c);
     
 }
private void populateState(){
     String[] cc = c.stateArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     hstate.setModel(c);
     
 }

private void populateCommunity(){
     String[] cc = co.communityArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     hcommunity.setModel(c);
     
 }
private void populateZipcode(){
     String[] cc = co.zipcodeArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     zipcode.setModel(c);
     
 }
private void populateHospitalname(){
     String[] cc = h.hospitalnameArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     hname.setModel(c);
     
 }
private void populateHospitaladd(){
     String[] cc = h.hospitaladdArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     hresidence.setModel(c);
     
 }

}

