/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package systemAdmin;



//import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.encounter;
import model.encounterArrayList;
//import java.util.Date;
import java.lang.String;
import javax.swing.DefaultComboBoxModel;
import model.Patient;
import model.doctorArrayList;
import model.hospitalArrayList;
import model.patientArrayList;
import patient.proPatient;
/**
 *
 * @author DELL
 */
public class encounterSysAdmin extends javax.swing.JPanel {

    /**
     * Creates new form encounterSysAdmin
     */
    encounterArrayList e;
    patientArrayList p;
    doctorArrayList d;
    hospitalArrayList h;
    public encounterSysAdmin(patientArrayList p,doctorArrayList d,hospitalArrayList h,encounterArrayList e) {
        initComponents();
        this.e=e;
        this.p=p;
        this.h=h;
        this.d=d;
        populateTable();
        populatePatientName();
        populatePatientUsername();
        populateDoctorName();
        populateDoctorUsername();
        populateHospitalname();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlePatient = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablee = new javax.swing.JTable();
        encounterid = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        view = new javax.swing.JButton();
        lblName7 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblName8 = new javax.swing.JLabel();
        lblName9 = new javax.swing.JLabel();
        lblName10 = new javax.swing.JLabel();
        patientname = new javax.swing.JComboBox<>();
        hospitalname = new javax.swing.JComboBox<>();
        patientusername = new javax.swing.JComboBox<>();
        doctorname = new javax.swing.JComboBox<>();
        doctorusername = new javax.swing.JComboBox<>();
        time = new javax.swing.JTextField();
        roomno = new javax.swing.JTextField();
        encounterdate = new javax.swing.JTextField();

        titlePatient.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        titlePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePatient.setText("Encounter Details");
        titlePatient.setToolTipText("");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Encounter Id");

        tablee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Doctor Name", "Patient Name", "Encounter ID", "Hospital Name", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablee);

        lblName3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName3.setText("Hospital Name");

        lblName5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName5.setText("Doctor Username");

        lblName6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName6.setText("Doctor Name");

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        lblName7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName7.setText("Patient Username");

        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName1.setText("Patient Name");

        lblName8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName8.setText("Date");

        lblName9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName9.setText("Time");

        lblName10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName10.setText("Room No");

        doctorusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorusernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName1)
                            .addComponent(lblName5)
                            .addComponent(lblName8))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(encounterdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(encounterid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1137, 1137, 1137))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(665, 665, 665)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblName10)
                                            .addComponent(lblName9)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblName3)))
                                .addComponent(lblName6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblName7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(doctorusername, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(roomno)
                                        .addComponent(patientname, 0, 119, Short.MAX_VALUE)
                                        .addComponent(patientusername, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(hospitalname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctorname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(titlePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 983, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titlePatient)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(encounterid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName1)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientusername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hospitalname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName3))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(doctorname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName6)))
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorusername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName5))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName8)
                            .addComponent(encounterdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName9)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName10)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(706, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         int row = tablee.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this,"Please select row to delete");
            return;

        }

        DefaultTableModel model = (DefaultTableModel) tablee.getModel();
        encounter selectedep = (encounter)model.getValueAt(row, 0);

        e.deleteE(selectedep);
        JOptionPane.showMessageDialog(this,"Encounter deleted");

        populateTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here
        int flag =1;
         String ss1 = encounterid.getText();
        
         if(ss1.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
           return;
        }
        char[] chars = ss1.toCharArray();
        for(char c : chars)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
               return;   
            }
        }
        int s1 = Integer.parseInt(ss1);
        
        for (encounter epp:e.getE()){
            
                if(s1 == (epp.getEncounterNo()))
                {
                    flag=0;
                    JOptionPane.showMessageDialog(this,"Encounter ID exists"); 
                    return;
                    
                }
            
        }
        
        String s2 = (String)patientname.getSelectedItem(); 
        if(s2.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars2 = s2.toCharArray();
        for(char c : chars2)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
        String s3 = (String)patientusername.getSelectedItem(); 
        if(s3.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Username cannot be empty");
           return;                     
        }   
        String s4 = (String)hospitalname.getSelectedItem(); 
        if(s4.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars4 = s4.toCharArray();
        for(char c : chars4)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
        String s5 = (String)doctorname.getSelectedItem(); 
        if(s5.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars5 = s5.toCharArray();
        for(char c : chars5)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
         String s6 = (String)doctorusername.getSelectedItem(); 
        if(s6.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Username cannot be empty");
           return;                     
        }
        
        
        String s7 = encounterdate.getText();
        if(s7.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Please enter date");
           return;                     
        }
         if (s7.length()<10){
             flag=0;
            JOptionPane.showMessageDialog(this,"Please enter correct date in format mm/dd/yyyy" );
            return;
        }
        
        StringBuffer sBuffer = new StringBuffer(s7);
        String mm;
        String dd;
        String yr;

        mm = sBuffer.substring(0,2);
        dd = sBuffer.substring(3,5);
        yr = sBuffer.substring(6,10);

        
        if(mm.matches("0[1-9]|1[0-2]") && dd.matches("0[1-9]|[12][0-9]|3[01]") && yr.matches("(19|20)\\d\\d"))
        {
          
        }
        else
        {
            flag=0;
         JOptionPane.showMessageDialog(this, "Please enter correct date in format mm/dd/yyyy");
         return;
        }
        String s8 = (String)time.getText();
        if(s8.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Please enter time");
           return;                     
        }
        
        
        String s9 = roomno.getText();
        if(s9.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Room No cannot be empty");
           return;                     
        }
        for (encounter epp:e.getE()){
            if (patientusername.getSelectedItem().equals(epp.getPatientUsername())){
                if(encounterid.getText().equals(epp.getEncounterNo()))
                {
                    flag=0;
                    JOptionPane.showMessageDialog(this,"Encounter ID exists for this patient"); 
                    return;
                    
                }
            }
        }
        for (encounter epp:e.getE()){
            if (doctorusername.getSelectedItem().equals(epp.getDoctorUsername())){
                if(encounterid.getText().equals(epp.getEncounterNo()))
                {
                    flag=0;
                    JOptionPane.showMessageDialog(this,"Encounter ID exists for this doctor"); 
                    return;
                           
                }
            }
        }
        
        if(flag==1)
        {
            encounter en = e.addNewE();
            en.setEncounterNo(s1);
            en.setPatientName(s2);
            en.setPatientUsername(s3);
            en.setHospitalName(s4);
            en.setDoctorName(s5);
            en.setDoctorUsername(s6);
            en.setEncounterDate(s7);
            en.setEncounterTime(s8);
            en.setRoomNo(s9);
            
            JOptionPane.showMessageDialog(this,"Encounter created successfully"); 
          
           populateTable();
                       
        }
        
        encounterid.setText("");
        patientname.setSelectedItem("select");
        patientusername.setSelectedItem("select");
        hospitalname.setSelectedItem("select");
        doctorname.setSelectedItem("select");
        doctorusername.setSelectedItem("select");
        encounterdate.setText("");
        time.setText("");
        roomno.setText("");
        
        
    }//GEN-LAST:event_createActionPerformed

    private void doctorusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorusernameActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int row = tablee.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tablee.getModel();
        encounter selectedep = (encounter)model.getValueAt(row, 0);
        e.deleteE(selectedep);
        
        int flag =1;
         String ss1 = encounterid.getText();
        
         if(ss1.equals(""))
        {
            flag=0;
           JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
           return;
        }
        char[] chars = ss1.toCharArray();
        for(char c : chars)
        {
            if(Character.isAlphabetic(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Id field cannot be empty or contain alphabet"); 
               return;   
            }
        }
        
        int s1 = Integer.parseInt(ss1);
        for (encounter epp:e.getE()){
            
                if(s1 == (epp.getEncounterNo()))
                {
                    flag=0;
                    JOptionPane.showMessageDialog(this,"Encounter ID exists"); 
                    return;
                    
                }
            
        }
        
        String s2 = (String)patientname.getSelectedItem(); 
        if(s2.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars2 = s2.toCharArray();
        for(char c : chars2)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
        String s3 = (String)patientusername.getSelectedItem(); 
        if(s3.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Username cannot be empty");
           return;                     
        }   
        String s4 = (String)hospitalname.getSelectedItem(); 
        if(s4.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars4 = s4.toCharArray();
        for(char c : chars4)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
        String s5 = (String)doctorname.getSelectedItem(); 
        if(s5.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
           return;                     
        }   
        char[] chars5 = s5.toCharArray();
        for(char c : chars5)
        {
            if(Character.isDigit(c))
            {
               flag=0;
               JOptionPane.showMessageDialog(this,"Name field cannot be empty or contain numbers");
               return;   
            }
        }
         String s6 = (String)doctorusername.getSelectedItem(); 
        if(s6.equals("select"))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Username cannot be empty");
           return;                     
        }
        
        
        String s7 = encounterdate.getText();
        if(s7.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Please enter date");
           return;                     
        }
         if (s7.length()<10){
             flag=0;
            JOptionPane.showMessageDialog(this,"Please enter correct date in format mm/dd/yyyy" );
            return;
        }
        
//        StringBuffer sBuffer = new StringBuffer(s7);
//        String mm;
//        String dd;
//        String yr;
//
//        mm = sBuffer.substring(0,2);
//        dd = sBuffer.substring(3,5);
//        yr = sBuffer.substring(6,10);
//
//        
//        if(mm.matches("0[1-9]|1[0-2]") && dd.matches("0[1-9]|[12][0-9]|3[01]") && yr.matches("(19|20)\\d\\d"))
//        {
//          
//        }
//        else
//        {
//            flag=0;
//         JOptionPane.showMessageDialog(this, "Please enter correct date in format mm/dd/yyyy");
//         return;
//        }
        
        String s8 =time.getText();
        if(s8.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Please enter time");
           return;                     
        }
        
        
        String s9 = roomno.getText();
        if(s9.equals(""))
        {
           flag=0;
           JOptionPane.showMessageDialog(this,"Room No cannot be empty");
           return;                     
        }
        for (encounter epp:e.getE()){
            if (patientusername.getSelectedItem().equals(epp.getPatientUsername())){
                if(encounterid.getText().equals(epp.getEncounterNo()))
                {
                    flag=0;
                    JOptionPane.showMessageDialog(this,"Encounter ID exists for this patient"); 
               return;
                    
                }
            }
        }
        for (encounter epp:e.getE()){
            if (doctorusername.getSelectedItem().equals(epp.getDoctorUsername())){
                if(encounterid.getText().equals(epp.getEncounterNo()))
                {
                    flag=0;
                    JOptionPane.showMessageDialog(this,"Encounter ID exists for this doctor"); 
               return;
                           
                }
            }
        }
        
        if(flag==1)
        {
            encounter en = e.addNewE();
            en.setEncounterNo(s1);
            en.setPatientName(s2);
            en.setPatientUsername(s3);
            en.setHospitalName(s4);
            en.setDoctorName(s5);
            en.setDoctorUsername(s6);
            en.setEncounterDate(s7);
            en.setEncounterTime(s8);
            en.setRoomNo(s9);
            
            JOptionPane.showMessageDialog(this,"Encounter created successfully"); 
          
           populateTable();
                       
        }
        
        encounterid.setText("");
        patientname.setSelectedItem("select");
        patientusername.setSelectedItem("select");
        hospitalname.setSelectedItem("select");
        doctorname.setSelectedItem("select");
        doctorusername.setSelectedItem("select");
        encounterdate.setText("");
        time.setText("");
        roomno.setText("");
        
    
    }//GEN-LAST:event_updateActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        int row = tablee.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tablee.getModel();
        encounter selectedep = (encounter)model.getValueAt(row, 0);
        
                encounterid.setText(String.valueOf(selectedep.getEncounterNo()));
                patientname.setSelectedItem(String.valueOf(selectedep.getPatientName()));
                patientusername.setSelectedItem(String.valueOf(selectedep.getPatientUsername()));
                hospitalname.setSelectedItem(String.valueOf(selectedep.getHospitalName()));
                doctorname.setSelectedItem(String.valueOf(selectedep.getDoctorName()));
                doctorusername.setSelectedItem(String.valueOf(selectedep.getDoctorUsername()));
                encounterdate.setText(String.valueOf(selectedep.getEncounterDate()));
                time.setText(String.valueOf(selectedep.getEncounterTime()));
                roomno.setText(String.valueOf(selectedep.getRoomNo()));
    }//GEN-LAST:event_viewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> doctorname;
    private javax.swing.JComboBox<String> doctorusername;
    private javax.swing.JTextField encounterdate;
    private javax.swing.JTextField encounterid;
    private javax.swing.JComboBox<String> hospitalname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JComboBox<String> patientname;
    private javax.swing.JComboBox<String> patientusername;
    private javax.swing.JTextField roomno;
    private javax.swing.JTable tablee;
    private javax.swing.JTextField time;
    private javax.swing.JLabel titlePatient;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
          DefaultTableModel model = (DefaultTableModel) tablee.getModel();
          model.setRowCount(0);
        
        for (encounter ep:e.getE()){
            
            Object[] row = new Object[6];
            row[0] = ep;
            row[1] = ep.getPatientName();
            row[2] = ep.getEncounterNo();
            row[3] = ep.getHospitalName();
            row[4] = ep.getEncounterDate();
            row[5] = ep.getEncounterTime();
            
            
            
            model.addRow(row);
}     
   
        
   }

private void populatePatientName(){
     String[] cc = p.patientNameArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     patientname.setModel(c);
     
 }
private void populatePatientUsername(){
     String[] cc = p.patientUsernameArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     patientusername.setModel(c);
     
 }
private void populateDoctorName(){
     String[] cc = d.doctorNameArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     doctorname.setModel(c);
     
 }
private void populateDoctorUsername(){
     String[] cc = d.doctorUsernameArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     doctorusername.setModel(c);
     
 }
    
 private void populateHospitalname(){
     String[] cc = h.hospitalnameArray();
     DefaultComboBoxModel c = new DefaultComboBoxModel(cc);
     hospitalname.setModel(c);
     
 }
}
