/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doctor;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import login.homePage;
import model.Doctor;
import model.VitalSigns;
import model.cityArrayList;
import model.communityArrayList;
import model.doctorArrayList;
import model.encounter;
import model.encounterArrayList;
import model.hospitalArrayList;
import model.houseArrayList;
import model.patientArrayList;
import model.vitalsignsArrayList;

/**
 *
 * @author DELL
 */
public class doctorPanel extends javax.swing.JFrame {

    /**
     * Creates new form doctorPanel
     */
    doctorArrayList d;
    hospitalArrayList h;
    cityArrayList c;
    communityArrayList co;
    houseArrayList ho;
    encounterArrayList e;
    patientArrayList p;
    vitalsignsArrayList vs;
    public String[] getdata = new String[1];
    public doctorPanel(doctorArrayList d,hospitalArrayList h,cityArrayList c,communityArrayList co,houseArrayList ho,encounterArrayList e,patientArrayList p,vitalsignsArrayList vs) {
        initComponents();
        this.d = d;
        this.c=c;
        this.co=co;
        this.ho=ho;
        this.h=h;
        this.e=e;
        this.p =p;
        this.vs=vs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_split = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        encounter = new javax.swing.JButton();
        vitalsign = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        encounter.setText("Encounter");
        encounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterActionPerformed(evt);
            }
        });

        vitalsign.setText("Vital Signs");
        vitalsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalsignActionPerformed(evt);
            }
        });

        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vitalsign, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(encounter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(profile)
                .addGap(51, 51, 51)
                .addComponent(encounter)
                .addGap(46, 46, 46)
                .addComponent(vitalsign)
                .addGap(46, 46, 46)
                .addComponent(home)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        dp_split.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );

        dp_split.setRightComponent(jPanel2);

        display.setBackground(new java.awt.Color(242, 242, 242));
        display.setColumns(20);
        display.setForeground(new java.awt.Color(242, 242, 242));
        display.setRows(5);
        display.setBorder(null);
        display.setCaretColor(new java.awt.Color(242, 242, 242));
        display.setDisabledTextColor(new java.awt.Color(242, 242, 242));
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dp_split, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 472, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dp_split, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        Profile pp = new Profile(d);
        dp_split.setRightComponent(pp);
        Profile.username.setText(display.getText());
        for (Doctor epp:d.getD()){
            if (Profile.username.getText().equals(epp.getUsername())){  
                Profile.name.setText(String.valueOf(epp.getName()));
                Profile.age.setText(String.valueOf(epp.getAge()));
                Profile.gender.setSelectedItem(String.valueOf(epp.getGender()));
                Profile.hresidence.setText(String.valueOf(epp.getHospitalResidence()));
                Profile.hcommunity.setText(String.valueOf(epp.getCommunity()));
                Profile.doctorid.setText(String.valueOf(epp.getDoctorId()));
                Profile.hcity.setText(String.valueOf(epp.getCity()));
                Profile.hname.setText(String.valueOf(epp.getHospitalName()));
                Profile.cellphone.setText(String.valueOf(epp.getCellPhone()));
                Profile.username.setText(String.valueOf(epp.getUsername()));
                Profile.password.setText(String.valueOf(epp.getPassword()));
                Profile.zipcode.setText(String.valueOf(epp.getZipcode()));
                Profile.hstate.setText(String.valueOf(epp.getState()));
                Profile.hcountry.setText(String.valueOf(epp.getCountry()));
            }
        }
        
    }//GEN-LAST:event_profileActionPerformed

    private void encounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterActionPerformed
        // TODO add your handling code here:
        encounterDoctor pp = new encounterDoctor(e,p,d,h);
        dp_split.setRightComponent(pp);
        encounterDoctor.doctorusername.setText(display.getText());
           

        DefaultTableModel model = (DefaultTableModel) encounterDoctor.tablede.getModel();
        model.setRowCount(0);
        for (encounter ep:e.getE()){
            if (encounterDoctor.doctorusername.getText().equals(ep.getDoctorUsername())){  
                
                  Object[] row = new Object[4];
                    row[0] = ep;
                    row[1] = ep.getPatientName();
                    row[2] = ep.getEncounterNo();
                    row[3] = ep.getEncounterDate();
             model.addRow(row); 
            }   
        }
    }//GEN-LAST:event_encounterActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        homePage hframe = new homePage(p,d,h,c,co,ho,e,vs);
            hframe.setVisible(true);
            this.setVisible(false);
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void vitalsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalsignActionPerformed
        // TODO add your handling code here:
        vitalsignsDoc vsframe = new vitalsignsDoc(p,d,h,e,vs);
        dp_split.setRightComponent(vsframe);
//        vitalsigns.doctorusername.setText(display.getText());
           

//        DefaultTableModel model = (DefaultTableModel) vitalsigns.tablevs.getModel();
//        model.setRowCount(0);
//        for (VitalSigns ep:vs.getVs()){
//            if (vitalsigns.doctorusername.getText().equals(ep.getDoctorUsername())){  
//                
//                        Object[] row = new Object[3];      
//                        row[0] = ep;
//                        row[1] = ep.getEncounterNo();
//                        row[2] = ep.getHospitalName();
//                        model.addRow(row);
//                        
//            }   
//        }
//        
    }//GEN-LAST:event_vitalsignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new doctorPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea display;
    private javax.swing.JSplitPane dp_split;
    private javax.swing.JButton encounter;
    private javax.swing.JButton home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton profile;
    private javax.swing.JButton vitalsign;
    // End of variables declaration//GEN-END:variables


}
