/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patient;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.homePage;
import model.Patient;
import model.cityArrayList;
import model.communityArrayList;
import model.doctorArrayList;
import model.encounter;
import model.encounterArrayList;
import model.hospitalArrayList;
import model.houseArrayList;
import model.patientArrayList;
import model.vitalsignsArrayList;



/**
 *
 * @author DELL
 */
public class patientPanel extends javax.swing.JFrame {

    /**
     * Creates new form patient
     */
   patientArrayList p;
    doctorArrayList d;
    hospitalArrayList h;
    cityArrayList c;
    communityArrayList co;
    houseArrayList ho;
    encounterArrayList e;
    vitalsignsArrayList vs;
    public String[] getdata = new String[1];
    public patientPanel(patientArrayList p,doctorArrayList d,hospitalArrayList h,cityArrayList c,communityArrayList co,houseArrayList ho,encounterArrayList e,vitalsignsArrayList vs) {
        initComponents();
        this.h = h;
        this.p =  p;
        this.d = d; 
        this.c=c;
        this.co=co;
        this.ho=ho;
        this.e=e;  
        this.vs=vs;
        
       
        
    }
    
    
        
    
   
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp_split = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        profile = new javax.swing.JButton();
        home = new javax.swing.JButton();
        searchdoctor = new javax.swing.JButton();
        encounter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        searchdoctor.setText("Search Doctor");
        searchdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdoctorActionPerformed(evt);
            }
        });

        encounter.setText("Encounter History");
        encounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(encounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchdoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(profile)
                .addGap(37, 37, 37)
                .addComponent(searchdoctor)
                .addGap(34, 34, 34)
                .addComponent(encounter)
                .addGap(35, 35, 35)
                .addComponent(home)
                .addContainerGap(479, Short.MAX_VALUE))
        );

        pp_split.setLeftComponent(jPanel1);

        display.setBackground(new java.awt.Color(242, 242, 242));
        display.setForeground(new java.awt.Color(204, 204, 204));
        display.setBorder(null);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(662, Short.MAX_VALUE))
        );

        pp_split.setRightComponent(jPanel2);

        panel1.setPreferredSize(new java.awt.Dimension(644, 425));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pp_split, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp_split)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        proPatient pp = new proPatient(p);
        pp_split.setRightComponent(pp);
        proPatient.username.setText(display.getText());
        
        for (Patient epp:p.getP()){
            if (proPatient.username.getText().equals(epp.getUsername())){               
                                              
                    proPatient.name.setText(epp.getName());
                    proPatient.age.setText(String.valueOf(epp.getAge()));
                    proPatient.gender.setSelectedItem(epp.getGender());
                    proPatient.residence.setText(epp.getResidence());
                    proPatient.cellphone.setText(String.valueOf(epp.getCellPhone()));
                    proPatient.community.setText(epp.getCommunity());
                    proPatient.city.setText(epp.getCity());
                    proPatient.patientid.setText(String.valueOf(epp.getPatientId()));
                    proPatient.pass.setText(epp.getPassword());
                    proPatient.zipcode.setText(String.valueOf(epp.getZipcode()));
                    proPatient.state.setText(String.valueOf(epp.getState()));
                    proPatient.country.setText(String.valueOf(epp.getCountry()));
                    
                             
            }}
        
                 
        pp.setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        homePage hframe = new homePage(p,d,h,c,co,ho,e,vs);
            hframe.setVisible(true);
            this.setVisible(false);
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void searchdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdoctorActionPerformed
        // TODO add your handling code here:
         searchDoctor sd = new searchDoctor(d);
        pp_split.setRightComponent(sd);
    }//GEN-LAST:event_searchdoctorActionPerformed

    private void encounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterActionPerformed
        // TODO add your handling code here:
        encounterPatient pp = new encounterPatient(p,d,h,e);
        pp_split.setRightComponent(pp);
        encounterPatient.patientusername.setText(display.getText());
           

        DefaultTableModel model = (DefaultTableModel) encounterPatient.tablepe.getModel();
        model.setRowCount(0);
        for (encounter ep:e.getE()){
            if (encounterPatient.patientusername.getText().equals(ep.getPatientUsername())){  
                
                        Object[] row = new Object[3];      
                        row[0] = ep;
                        row[1] = ep.getEncounterNo();
                        row[2] = ep.getEncounterDate();
                        model.addRow(row);
                        
            }             
//                                              
//                encounterPatient.encounterid.setText(String.valueOf(epp.getEncounterNo()));
//                encounterPatient.patientname.setSelectedItem(String.valueOf(epp.getPatientName()));
//                encounterPatient.patientusername.setSelectedItem(String.valueOf(epp.getPatientUsername()));
//                encounterPatient.hospitalname.setSelectedItem(String.valueOf(epp.getHospitalName()));
//                encounterPatient.doctorname.setSelectedItem(String.valueOf(epp.getDoctorName()));
//                encounterPatient.doctorusername.setSelectedItem(String.valueOf(epp.getDoctorUsername()));
//                //date.setText(selectedep.getEncounterDate().toString());
//                encounterPatient.time.setSelectedItem(String.valueOf(epp.getEncounterTime()));
//                encounterPatient.roomno.setText(String.valueOf(epp.getRoomNo()));
//            }       
            }             
    }//GEN-LAST:event_encounterActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new patientPanel().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField display;
    private javax.swing.JButton encounter;
    private javax.swing.JButton home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel1;
    private javax.swing.JSplitPane pp_split;
    private javax.swing.JButton profile;
    private javax.swing.JButton searchdoctor;
    // End of variables declaration//GEN-END:variables


}
